{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 1,
    "last_updated": "2025-06-11T07:45:00.051805",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-5991",
      "publishedDate": "2025-06-11T07:33:41.071Z",
      "lastModifiedDate": "2025-06-11T07:33:41.071Z",
      "description": "There is a \"Use After Free\" vulnerability in Qt's QHttp2ProtocolHandler in the QtNetwork module. This only affects HTTP/2 handling, HTTP handling is not affected by this at all. This happens due to a race condition between how QHttp2Stream uploads the body of a\n POST request and the simultaneous handling of HTTP error responses.\n\nThis issue only affects Qt 6.9.0 and has been fixed for Qt 6.9.1.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://codereview.qt-project.org/c/qt/qtbase/+/643777",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "Qt",
          "vendor": "The Qt Company",
          "versions": [
            {
              "lessThan": "6.9.0",
              "status": "unaffected",
              "version": "0",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "6.9.0"
            },
            {
              "status": "unaffected",
              "version": "6.9.1"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-416 Use After Free"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}