{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 2,
    "last_updated": "2025-04-14T23:43:52.165292",
    "severity_distribution": {
      "critical": 1,
      "high": 0,
      "medium": 0,
      "low": 0,
      "none": 1
    }
  },
  "cves": [
    {
      "id": "CVE-2025-24797",
      "publishedDate": "2025-04-14T23:25:19.152Z",
      "lastModifiedDate": "2025-04-14T23:25:19.152Z",
      "description": "Meshtastic is an open source mesh networking solution. A fault in the handling of mesh packets containing invalid protobuf data can result in an attacker-controlled buffer overflow, allowing an attacker to hijack execution flow, potentially resulting in remote code execution. This attack does not require authentication or user interaction, as long as the target device rebroadcasts packets on the default channel. This vulnerability fixed in 2.6.2.",
      "severity": 9.4,
      "references": [
        {
          "url": "https://github.com/meshtastic/firmware/security/advisories/GHSA-33hw-xhfh-944r",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "meshtastic",
          "product": "firmware",
          "versions": [
            {
              "version": "< 2.6.2",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-119: Improper Restriction of Operations within the Bounds of a Memory Buffer",
        "CWE-122: Heap-based Buffer Overflow"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-32428",
      "publishedDate": "2025-04-14T23:29:40.494Z",
      "lastModifiedDate": "2025-04-14T23:29:40.494Z",
      "description": "Jupyter Remote Desktop Proxy allows you to run a Linux Desktop on a JupyterHub. jupyter-remote-desktop-proxy was meant to rely on UNIX sockets readable only by the current user since version 3.0.0, but when used with TigerVNC, the VNC server started by jupyter-remote-desktop-proxy were still accessible via the network. This vulnerability does not affect users having TurboVNC as the vncserver executable. This issue is fixed in 3.0.1.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/security/advisories/GHSA-vrq4-9hc3-cgp7",
          "type": "reference"
        },
        {
          "url": "https://github.com/jupyterhub/jupyter-remote-desktop-proxy/commit/7dd54c25a4253badd8ea68895437e5a66a59090d",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "jupyterhub",
          "product": "jupyter-remote-desktop-proxy",
          "versions": [
            {
              "version": ">= 3.0.0, < 3.0.1",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-668: Exposure of Resource to Wrong Sphere"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}