{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "total_count": 3,
    "last_updated": "2025-03-19T20:51:51.637277",
    "severity_distribution": {
      "critical": 0,
      "high": 0,
      "medium": 0,
      "low": 1,
      "none": 2
    }
  },
  "cves": [
    {
      "id": "CVE-2025-30258",
      "publishedDate": "2025-03-19T00:00:00.000Z",
      "lastModifiedDate": "2025-03-19T20:49:22.417Z",
      "description": "In GnuPG before 2.5.5, if a user chooses to import a certificate with certain crafted subkey data that lacks a valid backsig or that has incorrect usage flags, the user loses the ability to verify signatures made from certain other signing keys, aka a \"verification DoS.\"",
      "severity": 2.7,
      "references": [
        {
          "url": "https://lists.gnupg.org/pipermail/gnupg-announce/2025q1/000491.html",
          "type": "reference"
        },
        {
          "url": "https://dev.gnupg.org/T7527",
          "type": "reference"
        },
        {
          "url": "https://dev.gnupg.org/rG48978ccb4e20866472ef18436a32744350a65158",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "GnuPG",
          "vendor": "GnuPG",
          "versions": [
            {
              "lessThan": "2.5.5",
              "status": "affected",
              "version": "0",
              "versionType": "semver"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-754 Improper Check for Unusual or Exceptional Conditions"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-27785",
      "publishedDate": "2025-03-19T20:35:10.662Z",
      "lastModifiedDate": "2025-03-19T20:47:30.839Z",
      "description": "Applio is a voice conversion tool. Versions 3.2.8-bugfix and prior are vulnerable to arbitrary file read in train.py's `export_index` function. This issue may lead to reading arbitrary files on the Applio server. It can also be used in conjunction with blind server-side request forgery to read files from servers on the internal network that the Applio server has access to. As of time of publication, no known patches are available.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://securitylab.github.com/advisories/GHSL-2024-341_GHSL-2024-353_Applio/",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/blob/29b4a00e4be209f9aac51cd9ccffcc632dfb2973/tabs/train/train.py#L273",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/blob/29b4a00e4be209f9aac51cd9ccffcc632dfb2973/tabs/train/train.py#L816",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "IAHispano",
          "product": "Applio",
          "versions": [
            {
              "version": "<= 3.2.8-bugfix",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        "CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
      ],
      "fix_suggestion": "无法生成修复建议"
    },
    {
      "id": "CVE-2025-27781",
      "publishedDate": "2025-03-19T20:22:38.448Z",
      "lastModifiedDate": "2025-03-19T20:48:03.243Z",
      "description": "Applio is a voice conversion tool. Versions 3.2.8-bugfix and prior are vulnerable to unsafe deserialization in inference.py. `model_file` in inference.py as well as `model_file` in tts.py take user-supplied input (e.g. a path to a model) and pass that value to the `change_choices` and later to `get_speakers_id` function, which loads that model with `torch.load` in inference.py (line 326 in 3.2.8-bugfix), which is vulnerable to unsafe deserialization. The issue can lead to remote code execution. A patch is available on the `main` branch of the repository.",
      "severity": "N/A",
      "references": [
        {
          "url": "https://securitylab.github.com/advisories/GHSL-2024-341_GHSL-2024-353_Applio/",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/commit/eb21d9dd349a6ae1a28c440b30d306eafba65097",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/blob/29b4a00e4be209f9aac51cd9ccffcc632dfb2973/tabs/inference/inference.py#L325",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/blob/29b4a00e4be209f9aac51cd9ccffcc632dfb2973/tabs/inference/inference.py#L338-L345",
          "type": "reference"
        },
        {
          "url": "https://github.com/IAHispano/Applio/blob/29b4a00e4be209f9aac51cd9ccffcc632dfb2973/tabs/tts/tts.py#L50-L57",
          "type": "reference"
        }
      ],
      "affected": [
        {
          "vendor": "IAHispano",
          "product": "Applio",
          "versions": [
            {
              "version": "<= 3.2.8-bugfix",
              "status": "affected"
            }
          ]
        }
      ],
      "problemType": [
        "CWE-502: Deserialization of Untrusted Data"
      ],
      "fix_suggestion": "无法生成修复建议"
    }
  ]
}